# Generated by Django 3.0.3 on 2020-02-08 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quest_text',
            new_name='question_text',
        ),
    ]
