# Generated by Django 3.0.3 on 2020-02-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200208_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='choice',
        ),
    ]
