# Generated by Django 3.0.3 on 2020-02-09 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200209_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice',
            new_name='question',
        ),
    ]
