# Generated by Django 3.0.3 on 2020-02-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(choices=[('NG', 'Nguyen'), ('LE', 'LE'), ('PH', 'Pham')], max_length=100),
        ),
    ]
