# Generated by Django 3.0.3 on 2020-04-15 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_result', to='polls.Choice'),
        ),
        migrations.AlterField(
            model_name='result',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_result', to='polls.Question'),
        ),
    ]
